# Background and foreground colors
background = #00071A
foreground = #DBE5FC

# Standard colors
palette = 0=#00071A
palette = 1=#ff5b52
palette = 2=#78c75f
palette = 3=#ffc73d
palette = 4=#4c6eff
palette = 5=#ff5fa8
palette = 6=#2fd1dc
palette = 7=#DBE5FC

# Bright colors
palette = 8=#5b5f64
palette = 9=#ff7a6b
palette = 10=#8eec5b
palette = 11=#ffc73d
palette = 12=#6e8bff
palette = 13=#ff82c0
palette = 14=#5ee3ec
palette = 15=#d7eaff
