$color = rgba(0, 7, 26, 1)
$inner_color = rgba(0, 7, 26, 0.66)
$outer_color = rgba(74, 104, 255, 1)
$font_color = rgba(219, 229, 252, 1)
$placeholder_color = rgba(219, 229, 252, 0.7)
$check_color = rgba(74, 144, 28, 1)
