background            #00071A
foreground            #DBE5FC

# black
color0  #00071A
color8  #5b5f64

# red
color1  #ff5b52
color9  #ff7a6b

# green
color2  #78c75f
color10 #8eec5b

# yellow
color3  #ffc73d
color11 #ffc73d

# blue
color4  #4c6eff
color12 #6e8bff

# magenta
color5  #ff5fa8
color13 #ff82c0

#cyan
color6  #2fd1dc
color14 #5ee3ec

#white
color7  #DBE5FC
color15 #d7eaff


